remote_theme: b2a3e8/jekyll-theme-console
markdown: kramdown
title: meatbag.xyz
description: "@meatbagMB"
github:
  is_project_page: false
show_downloads: false
footer: 'follow me on <a href="https://twitter.com/meatbagMB" target="_blank">twitter</a>'
header_pages:
  - index.md
  - about.md
  - contact.md
